### ISSUE TITLE
Stuck in Preloader

### ISSUE THREAD

**Issue by vndrewboss** [fidalgodev/movie-library-react#2]
I run npm run dev, but it won't load the data. Stuck at preloader!

**Comment by fidalgodev** [comment]
> I run npm run dev, but it won't load the data. Stuck at preloader!

Because you didn't followed the instructions and created the file with your API key. Either that, or your internet provider blocks requests to the API. Had this happening with a person from India, because the government had very restrict rules with internet. Either way, check your console and see what errors you are getting. This isn't an issue with the Web App.
